name: Deploy Santino to GitHub Pages

on:
  push:
    branches:
      - crypto-bot
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (santino/curentVersion)
        uses: actions/upload-pages-artifact@v3
        with:
          path: santino/curentVersion

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
